
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubuntu18"

  #config.vm.network "forwarded_port", guest: 8080, host: 80

  config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  #Linux
  #config.vm.synced_folder "~/proyecto/lab02", "/home/vagrant/docker"

  #Windows
  config.vm.synced_folder "C:\\proyecto\\lab02", "/home/vagrant/docker"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "VM-ubuntu18"
    vb.memory = "1024"
    vb.cpus = 2

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. 
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
    sudo apt install neofetch tree -y
  SHELL

  config.vm.provision :docker

  #config.vm.provision "docker" do |d|
  #  d.pull_images "wordpress"
  # d.pull_images "mysql"
  #end
  
  #docker images
  #docker ps
  #docker run -d --name mysql-container -e MYSQL_ROOT_PASSWORD=my-mysql@123 mysql
  #docker run -d --name wordpress-container --link mysql-container:mysql -p 80:80 wordpress


  #docker run -d --name nginx-container -v /home/vagrant/docker:/usr/share/nginx/html -p 80:80 nginx:alpine
  #docker ps
  #docker images
  #docker exec -it nginx-container bash
  #docker stop nginx-container
  #docker rm nginx-container
  #docker ps
  #docker rmi -f imagen-id
  #docker build -t nombre-imagen .

end
