
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian2"

  #config.vm.network "forwarded_port", guest: 8080, host: 80

  config.vm.network "private_network", ip: "192.168.33.32"

  # config.vm.network "public_network", ip: "192.168.100.32"

  #Linux
  #config.vm.synced_folder ".", "/home/vagrant/docker"

  #Windows
  config.vm.synced_folder ".", "/home/vagrant/docker"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "VM-debian2"
    vb.memory = "1024"
    vb.cpus = 2

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
    sudo apt install tree neofetch -y
  SHELL

  config.vm.provision :docker
  
  #docker pull mysql:8.0
  #docker pull wordpress:5.8.2
  
  #docker run -d --name mysqlwp -e MYSQL_ROOT_PASSWORD=wordpresspwd -e MYSQL_DATABASE=wordpress_db -e MYSQL_USER=wordpress_user -e MYSQL_PASSWORD=wordpress123 mysql:8.0
  #docker run -d --name wordpress --link mysqlwp:mysql -p 80:80 -e WORDPRESS_DB_NAME=wordpress_db -e WORDPRESS_DB_USER=wordpress_user -e WORDPRESS_DB_PASSWORD=wordpress123 wordpress:5.8.2
  #sudo docker exec -it 4ae700062f63 mysql -u wordpress_user -p wordpress123
  #sudo docker exec -it contenedor-id bash
end
