
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian4"

  #config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.12"

  #config.vm.network "public_network", ip: "192.168.33.12"

  #Windows
  config.vm.synced_folder "C:\\proyecto\\lab04", "/home/vagrant/docker"

  #Linux
  #config.vm.synced_folder "~/proyecto/lab04", "/home/vagrant/docker"
  
  config.vm.provider "virtualbox" do |vb|

    vb.name = "VM-debian4"  
    vb.memory = "1024"
    vb.cpus = 2

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
    sudo apt install tree neofetch -y
  SHELL

  config.vm.provision :docker
  config.vm.provision :docker_compose


end


  #vagrant plugin install vagrant-docker-compose 
  #vagrant plugin install vagrant-share
  #vagrant plugin list
  #vagrant plugin uninstall