# Copyright (c) 2014-2022 Bjoern Kimminich & the OWASP Juice Shop contributors.
# SPDX-License-Identifier: MIT

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2110"
  config.vm.hostname = "ubuntu"

   config.vm.provider "virtualbox" do |vb|

    vb.name = "VM-ubuntu"  
    vb.memory = "1024"
    vb.cpus = 2

  end

  config.vm.network "private_network", ip: "192.168.33.34"
  config.vm.provision "file", source: "./default.conf", destination: "/tmp/juice-shop/default.conf"
  config.vm.provision :shell, path: "bootstrap.sh"
end