
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian4"

  #config.vm.network "forwarded_port", guest: 8080, host: 80

  config.vm.network "private_network", ip: "192.168.33.35"

  # config.vm.network "public_network", ip: "192.168.100.35"

  #Linux
  #config.vm.synced_folder ".", "/home/vagrant/docker"

  #Windows
  config.vm.synced_folder ".", "/home/vagrant/docker"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "VM-debian4"
    vb.memory = "1024"
    vb.cpus = 2

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
    sudo apt install tree neofetch -y
  SHELL

  config.vm.provision :docker
  
  
  #docker run --name phpipam-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -v /my_dir/phpipam:/var/lib/mysql -d mysql:5.6
  #docker run -d -p 80:80 -e MYSQL_ENV_MYSQL_ROOT_PASSWORD=my-secret-pw --name ipam --link phpipam-mysql:mysql pierrecdn/phpipam
  #http://192.168.33.35

  #sudo docker exec -it contenedor-id bash

  
end
