#https://docs.docker.com/samples/django/

version: "3.7"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/home/vagrant/docker
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

#sudo docker-compose run web django-admin startproject config .
#edit settings.py allowed_hosts and database.

    #sudo docker-compose run web python manage.py migrate
    #sudo docker-compose run web python manage.py createsuperuser admin admin



#docker-compose up -d *
  # http://192.168.33.33
#docker-compose down  *

#sudo docker exec -it contenedor-id bash
#docker-compose build
