
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ubuntu20"

  #config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.11"

  # config.vm.network "public_network"

  config.vm.synced_folder "C:\\proyecto\\lab03", "/home/vagrant/docker"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "VM-ubuntu20"
    vb.memory = "1024"
    vb.cpus = 2

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
  SHELL

  #docker run -d --name nginx-container -v /home/vagrant/docker:/usr/share/nginx/html -p 8080:80 nginx:alpine
  config.vm.provision :docker

  #vagrant plugin install vagrant-docker-compose 
  #vagrant plugin install vagrant-share
  #vagrant plugin list
  #vagrant plugin uninstall 
  config.vm.provision :docker_compose

end
