
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian3"

  #config.vm.network "forwarded_port", guest: 8080, host: 80

  config.vm.network "private_network", ip: "192.168.33.33"

  # config.vm.network "public_network", ip: "192.168.100.33"

  #Linux
  #config.vm.synced_folder ".", "/home/vagrant/docker"

  #Windows
  config.vm.synced_folder ".", "/home/vagrant/docker"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "VM-debian3"
    vb.memory = "1024"
    vb.cpus = 2

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
    sudo apt install tree neofetch docker.io docker-compose -y
  SHELL

  config.vm.provision :docker
    

  
end
